### ISSUE TITLE
Pulling image is unauthorized

### ISSUE THREAD

**Issue by DoubtfulTurnip** [limmer55/streamdock#1]
docker run -d --name streamdock --network host --restart unless-stopped ghcr.io/limmer55/streamdock:latest
Unable to find image 'ghcr.io/limmer55/streamdock:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/limmer55/streamdock/manifests/latest": unauthorized.

**Comment by lkenner** [comment]
fixed :)  Could you please try again?
