### ISSUE TITLE
Unraid template

### ISSUE THREAD

**Issue by nwithan8** [limmer55/streamdock#9]
Hey, great app, have been looking for something just like this.

I made an Unraid template so users can easily install this Docker application from the Community Apps Store. Just a heads up in case you get a bump in people coming to this repo.

**Comment by lkenner** [comment]
> Hey, great app, have been looking for something just like this.
> 
> I made an Unraid template so users can easily install this Docker application from the Community Apps Store. Just a heads up in case you get a bump in people coming to this repo.

This is awesome, thank you!
